### ISSUE TITLE
Add a service package for unbound

### ISSUE THREAD

**Issue by 87-79-80-82** [NuTyX/packages-x86_64#110]
Hello,

Unbound require a service file for system V.
I modified a file that I found [here](https://github.com/NLnetLabs/unbound/blob/master/contrib/unbound.init). It works on my system but creating init scripts on NuTyX is a new thing for me. I'll drop the file here but I think a code review would be a good thing.

_(file rename to unbound.txt in order to be able to upload it here)_
[unbound.txt](https://github.com/NuTyX/packages-x86_64/files/9305112/unbound.txt)

### EDIT n°1
I only "fix" the start / stop / restart / status options. 

### EDIT n°2
I have an error when shutting down my machine when I add the file **/etc/rc.d/rc0.d/K40unbound**
Using the script manually ./unbound stop works
No idea why...
![unbound_init_kill_error](https://user-images.githubusercontent.com/110996347/184052192-c588508c-47b3-4e53-8154-b90cb240186c.jpg)

**Comment by tnut** [comment]
Is it absotly necessary to umount ${rootdir}/dev/log umount ${rootdir}/dev/urandom in the stop  command, I think it's done by another service (forgot the name)

**Comment by 87-79-80-82** [comment]
Hello @tnut 

I don't know if it's necessary to unmount these two files. All I can tell you is that: 
`grep -r "/dev/log" /etc/rc.d/init.d/`
`grep -r "/dev/urandom" /etc/rc.d/init.d/`
return no result other than the unbound file. 

About my second edit, I resolved the error by changing the line `killproc -p $pidfile $prog` with `killproc $exec` in the stop() function. Turning off my NuTyX now happens without error 😄
