### ISSUE TITLE
Tor service file not in the right place

### ISSUE THREAD

**Issue by 87-79-80-82** [NuTyX/packages-x86_64#111]
Hello,

When using
`cards install tor.service`

The service file is placed in the `/etc/rc.d` directory instead of `/etc/rc.d/init.d`.

I think this can be resolved by updating the Pkgfile:
Now: `install -m 0750 -D $SRC/tor.rc $PKG/etc/rc.d/tor`
Should be: `install -m 0750 -D $SRC/tor.rc $PKG/etc/rc.d/init.d/tor`

**Comment by tnut** [comment]
Absolutly :)

**Comment by spiky0011** [comment]
Done
