### ISSUE TITLE
Package request : proxychains

### ISSUE THREAD

**Issue by 87-79-80-82** [NuTyX/packages-x86_64#112]
Hello,

I'd like to have proxychains package added to NuTyX.
Here is the Pkgfile for NuTyX : http://ix.io/48b3
Tested in the VM that compiled it, works OK
Thanks !

_Constructed using the Arch Linux Pkgfile : https://github.com/archlinux/svntogit-community/tree/packages/proxychains-ng/trunk_

**Comment by spiky0011** [comment]
I,ll build it tommorow

**Comment by spiky0011** [comment]
done
